### ISSUE TITLE
[BUG] Can't build ui-playground

### ISSUE THREAD

**Issue by Karmalakas** [AdobeDocs/uxp-photoshop-plugin-samples#83]
Not sure if there's same issue with other plugins, but can't build `ui-playground`

I get
```
g:\___DEV___\Adobe\uxp-photoshop-plugin-samples-main\ui-playground
λ npm run build

> com.adobe.demo.ui.html.playground@1.0.0 build
> webpack --mode production

node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (g:\___DEV___\Adobe\uxp-photoshop-plugin-samples-main\ui-playground\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (g:\___DEV___\Adobe\uxp-photoshop-plugin-samples-main\ui-playground\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (g:\___DEV___\Adobe\uxp-photoshop-plugin-samples-main\ui-playground\node_modules\webpack\lib\NormalModule.js:471:10)
    at g:\___DEV___\Adobe\uxp-photoshop-plugin-samples-main\ui-playground\node_modules\webpack\lib\NormalModule.js:503:5
    at g:\___DEV___\Adobe\uxp-photoshop-plugin-samples-main\ui-playground\node_modules\webpack\lib\NormalModule.js:358:12
    at g:\___DEV___\Adobe\uxp-photoshop-plugin-samples-main\ui-playground\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (g:\___DEV___\Adobe\uxp-photoshop-plugin-samples-main\ui-playground\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (g:\___DEV___\Adobe\uxp-photoshop-plugin-samples-main\ui-playground\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at g:\___DEV___\Adobe\uxp-photoshop-plugin-samples-main\ui-playground\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (g:\___DEV___\Adobe\uxp-photoshop-plugin-samples-main\ui-playground\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at g:\___DEV___\Adobe\uxp-photoshop-plugin-samples-main\ui-playground\node_modules\babel-loader\lib\index.js:44:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
```

README says to use manifest from `dist`, which does not exist also

**Comment by Yamenalbadin** [comment]
This is a node.js v.18 related issue. 
in package.json, replace
    ```"build": "webpack --mode production",```
with 
    ```"build": "export NODE_OPTIONS=--openssl-legacy-provider && webpack --mode production",```

**Comment by aman-technyx** [comment]
my system config:
System:
    OS: macOS 14.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 286.70 MB / 16.00 GB
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
  Browsers:
    Chrome: 125.0.6422.142
    Safari: 17.5
  Packages:
    babel-loader: ^8.0.6 => 8.3.0 
    clean-webpack-plugin: ^2.0.2 => 2.0.2 
    copy-webpack-plugin: ^5.0.3 => 5.1.2 
    css-loader: ^6.8.1 => 6.11.0 
    file-loader: ^5.1.0 => 5.1.0 
    style-loader: ^1.1.3 => 1.3.0 
    webpack: ^5.91.0 => 5.91.0 
    webpack-cli: ^5.1.4 => 5.1.4 
    
    
    
    TRY TO RUN THESE COMMANDS IT WILL WORK 
    
    * rm -rf node_modules
    * rm package-lock.json
    * rm yarn.lock
    * npm install or check for npm outdated then run npm update 


after that run build or watch it will work
